export const translatedWords: { [key: string]: string } = {
    'عامل إيه': 'How are you?',
    عيب: 'Shame',
    عربية: 'Car',
    عايز: 'Want',
    أخويا: 'My brother',
    ألم: 'Pain',
    بحب: 'I love',
    بكره: 'I hate',
    بسرعة: 'Quickly',
    دلوقتي: 'Now',
    دكتور: 'Doctor',
    افرضها: 'Impose it',
    'احترم نفسك': 'Respect yourself',
    النهاردة: 'Today',
    'ارمي ورا ضهرك': 'Forget about it',
    فتان: 'Troublemaker',
    'في سرك': 'Keep it to yourself',
    فلوس: 'Money',
    'فكك مني': 'Leave me alone',
    جُمعة: 'Friday',
    حرامي: 'Thief',
    'حبة حبة': 'Little by little',
    'حلو أوي': 'Very nice',
    'حتة حتة': 'Piece by piece',
    كداب: 'Liar',
    خايف: 'Afraid',
    'خلي بالك': 'Be careful',
    خطيبتي: 'My fiancée',
    كولية: 'Kidney',
    كتاب: 'Book',
    مفيش: "There isn't",
    مكار: 'Cunning',
    منزل: 'House',
    'ماشي ماشي': 'Okay okay',
    ماشي: 'Okay',
    مراتي: 'My wife',
    مهندس: 'Engineer',
    مشوش: 'Confused',
    'مش عايز': "Don't want",
    أوضة: 'Room',
    'صباح الخير': 'Good morning',
    سبهللة: 'Messy',
    صادق: 'Honest',
    صاحبي: 'My friend',
    سباك: 'Plumber',
    شارع: 'Street',
    شباك: 'Window',
    تعبان: 'Tired',
    تمام: 'Fine',
    وحشني: 'I miss you',
    'واحدة واحدة': 'Slowly',
    يحتكر: 'Monopolize',
    يبكي: 'Cry',
    يضحك: 'Laugh',
    يالهووي: 'Oh my God!',
    يشتم: 'Insult',
};
